/**
 * Exercise library extension. Tuple: [name, muscleGroup, equipment, difficulty, MET, instructions]
 * Cables and stack machines use MACHINE equipment.
 */
export type ExTuple = [name: string, muscle: string, equipment: string, difficulty: string, met: number, instructions: string];

export const EXERCISES2: ExTuple[] = [
  // Chest
  ["Cable Fly", "CHEST", "MACHINE", "INTERMEDIATE", 3.5, "Set pulleys at chest height, slight elbow bend, bring handles together in a hugging arc, control the return."],
  ["Low-to-High Cable Fly", "CHEST", "MACHINE", "INTERMEDIATE", 3.5, "Pulleys low; sweep handles up and together to shoulder height, squeezing the upper chest."],
  ["High-to-Low Cable Fly", "CHEST", "MACHINE", "INTERMEDIATE", 3.5, "Pulleys high; drive handles down and together toward your hips, squeezing the lower chest."],
  ["Cable Crossover", "CHEST", "MACHINE", "ADVANCED", 4.0, "Step forward in a split stance, cross the handles past each other at the bottom of the arc."],
  ["Pec Deck Fly", "CHEST", "MACHINE", "BEGINNER", 3.5, "Forearms or hands on pads, squeeze the pads together, pause, open slowly."],
  ["Incline Dumbbell Press", "CHEST", "DUMBBELLS", "INTERMEDIATE", 5.0, "Bench at 30-45°, press dumbbells up and slightly back, lower to upper chest."],
  ["Decline Push-Up", "CHEST", "BODYWEIGHT", "INTERMEDIATE", 4.2, "Feet elevated on a bench, hands on floor, lower chest to floor and press up."],
  ["Diamond Push-Up", "ARMS", "BODYWEIGHT", "INTERMEDIATE", 4.2, "Hands together under chest forming a diamond, elbows tucked; lower and press."],
  ["Incline Barbell Press", "CHEST", "BARBELL", "INTERMEDIATE", 5.2, "Bench at 30-45°, lower the bar to the upper chest, press to lockout."],
  ["Dumbbell Pullover", "CHEST", "DUMBBELLS", "INTERMEDIATE", 3.8, "Lie across a bench, lower one dumbbell behind your head with soft elbows, pull back over the chest."],
  ["Chest Dips", "CHEST", "BODYWEIGHT", "ADVANCED", 5.0, "On parallel bars, lean forward, lower until shoulders are below elbows, press up."],
  ["Svend Press", "CHEST", "DUMBBELLS", "BEGINNER", 3.0, "Press a plate or dumbbell between flat palms straight out from the chest, squeezing hard."],
  // Back
  ["Chin-Up", "BACK", "BODYWEIGHT", "ADVANCED", 8.0, "Underhand grip, pull chin over the bar, lower with control."],
  ["Assisted Pull-Up (machine)", "BACK", "MACHINE", "BEGINNER", 5.0, "Kneel on the assist pad, pull chin over the bar; reduce assistance over time."],
  ["Close-Grip Lat Pulldown", "BACK", "MACHINE", "BEGINNER", 4.0, "Neutral close grip, pull the handle to the upper chest, elbows down."],
  ["Straight-Arm Pulldown", "BACK", "MACHINE", "INTERMEDIATE", 3.5, "Arms nearly straight, sweep the bar from shoulder height to thighs using the lats."],
  ["T-Bar Row", "BACK", "BARBELL", "INTERMEDIATE", 5.5, "Chest up over the pad or straddle the bar, row the handles to your torso."],
  ["Bent-Over Barbell Row", "BACK", "BARBELL", "INTERMEDIATE", 5.5, "Hinge to ~45°, flat back, row the bar to the lower ribs, lower under control."],
  ["Pendlay Row", "BACK", "BARBELL", "ADVANCED", 6.0, "Torso parallel to floor, row the bar explosively from a dead stop each rep."],
  ["Chest-Supported Dumbbell Row", "BACK", "DUMBBELLS", "BEGINNER", 4.5, "Chest on an incline bench, row dumbbells to your hips, squeeze the blades."],
  ["Single-Arm Cable Row", "BACK", "MACHINE", "BEGINNER", 4.0, "Row one handle to your hip, rotate slightly, resist the return."],
  ["Renegade Row", "BACK", "DUMBBELLS", "ADVANCED", 6.0, "In a plank on dumbbells, row one to the hip while bracing; alternate."],
  ["Kettlebell Row", "BACK", "KETTLEBELL", "BEGINNER", 4.5, "Hinge with a flat back, row the bell to the hip, lower slowly."],
  ["Band Row (seated)", "BACK", "BANDS", "BEGINNER", 3.5, "Band around feet, sit tall and row the handles to your waist."],
  ["Rack Pull", "BACK", "BARBELL", "INTERMEDIATE", 5.5, "Bar set at knee height, hinge and stand tall, squeezing the upper back."],
  ["Reverse Fly (rear delt, dumbbell)", "SHOULDERS", "DUMBBELLS", "BEGINNER", 3.0, "Hinge forward, raise dumbbells out to the sides with soft elbows, squeeze the rear delts."],
  ["Superman Hold", "BACK", "BODYWEIGHT", "BEGINNER", 2.8, "Lie face down, lift arms and legs off the floor, hold and breathe."],
  ["Bird Dog", "CORE", "BODYWEIGHT", "BEGINNER", 2.8, "On all fours, extend opposite arm and leg, pause, switch sides without rocking."],
  // Shoulders
  ["Arnold Press", "SHOULDERS", "DUMBBELLS", "INTERMEDIATE", 4.8, "Start palms facing you at chin height; rotate out as you press overhead."],
  ["Seated Dumbbell Shoulder Press", "SHOULDERS", "DUMBBELLS", "BEGINNER", 4.5, "Back supported, press dumbbells overhead without flaring the ribs."],
  ["Machine Shoulder Press", "SHOULDERS", "MACHINE", "BEGINNER", 4.0, "Adjust seat so handles start at shoulder height, press up, lower slowly."],
  ["Cable Lateral Raise", "SHOULDERS", "MACHINE", "INTERMEDIATE", 3.2, "Cable low at your side, raise the handle out to shoulder height, resist down."],
  ["Front Raise", "SHOULDERS", "DUMBBELLS", "BEGINNER", 3.0, "Raise dumbbells straight in front to shoulder height, lower slowly."],
  ["Upright Row", "SHOULDERS", "DUMBBELLS", "INTERMEDIATE", 4.0, "Pull dumbbells up along your body to chest height, elbows leading, wrists relaxed."],
  ["Dumbbell Shrugs", "SHOULDERS", "DUMBBELLS", "BEGINNER", 3.0, "Shrug shoulders straight up toward ears, pause, lower fully."],
  ["Push Press", "SHOULDERS", "BARBELL", "ADVANCED", 6.5, "Slight knee dip, drive the bar overhead using leg momentum, lower controlled."],
  ["Landmine Press", "SHOULDERS", "BARBELL", "INTERMEDIATE", 4.5, "One end of the bar anchored; press the other end up and forward from the shoulder."],
  ["Cable Face Pull", "SHOULDERS", "MACHINE", "BEGINNER", 3.2, "Rope at face height, pull toward your eyes with elbows high, external-rotating at the end."],
  ["Wall Handstand Hold", "SHOULDERS", "BODYWEIGHT", "ADVANCED", 4.5, "Kick up against a wall, arms locked, hold while breathing steadily."],
  // Arms
  ["Cable Tricep Pushdown", "ARMS", "MACHINE", "BEGINNER", 3.2, "Elbows pinned to sides, push the bar or rope down to full extension."],
  ["Overhead Cable Tricep Extension", "ARMS", "MACHINE", "INTERMEDIATE", 3.2, "Face away from the stack, extend the rope overhead, keep elbows narrow."],
  ["Skull Crushers", "ARMS", "BARBELL", "INTERMEDIATE", 3.5, "Lying down, lower the EZ bar to your forehead by bending elbows, extend back up."],
  ["Close-Grip Bench Press", "ARMS", "BARBELL", "INTERMEDIATE", 5.0, "Hands shoulder-width, elbows tucked, press focusing on the triceps."],
  ["EZ-Bar Curl", "ARMS", "BARBELL", "BEGINNER", 3.0, "Curl the EZ bar with elbows pinned; lower for a slow count."],
  ["Preacher Curl", "ARMS", "MACHINE", "BEGINNER", 3.0, "Arms on the pad, curl up, lower to a full stretch without bouncing."],
  ["Cable Bicep Curl", "ARMS", "MACHINE", "BEGINNER", 3.0, "Constant-tension curl from a low pulley, squeeze at the top."],
  ["Incline Dumbbell Curl", "ARMS", "DUMBBELLS", "INTERMEDIATE", 3.0, "On an incline bench, arms hanging back, curl through a long range."],
  ["Concentration Curl", "ARMS", "DUMBBELLS", "BEGINNER", 3.0, "Elbow braced on inner thigh, curl slowly, full squeeze at the top."],
  ["Zottman Curl", "ARMS", "DUMBBELLS", "INTERMEDIATE", 3.0, "Curl palms-up, rotate palms-down at the top, lower slowly."],
  ["Wrist Curls", "ARMS", "DUMBBELLS", "BEGINNER", 2.5, "Forearms on thighs, curl the wrists up and down through a full range."],
  ["Band Tricep Extension", "ARMS", "BANDS", "BEGINNER", 3.0, "Band anchored high, extend forearms down keeping elbows still."],
  ["Bench Dips (feet elevated)", "ARMS", "BODYWEIGHT", "INTERMEDIATE", 4.2, "Hands on a bench behind you, feet on another; lower to 90° and press."],
  // Legs & glutes
  ["Front Squat", "LEGS", "BARBELL", "ADVANCED", 6.0, "Bar racked on front delts, elbows high, squat deep keeping the torso upright."],
  ["Sumo Deadlift", "LEGS", "BARBELL", "INTERMEDIATE", 6.0, "Wide stance, toes out, grip inside knees; push the floor away and stand tall."],
  ["Barbell Romanian Deadlift", "LEGS", "BARBELL", "INTERMEDIATE", 5.5, "Soft knees, push hips back, lower the bar along your legs, drive hips forward."],
  ["Good Morning", "LEGS", "BARBELL", "ADVANCED", 4.5, "Bar on upper back, hinge at the hips with a flat back until a hamstring stretch, stand up."],
  ["Hack Squat (machine)", "LEGS", "MACHINE", "INTERMEDIATE", 5.5, "Back on the pad, lower to at least 90°, drive through mid-foot."],
  ["Leg Extension", "LEGS", "MACHINE", "BEGINNER", 3.5, "Extend knees to straight, pause, lower slowly without slamming the stack."],
  ["Lying Leg Curl", "LEGS", "MACHINE", "BEGINNER", 3.5, "Curl heels to glutes, pause, resist the way back."],
  ["Seated Calf Raise (machine)", "LEGS", "MACHINE", "BEGINNER", 3.0, "Pad on knees, raise heels high, stretch fully at the bottom."],
  ["Hip Abduction Machine", "GLUTES", "MACHINE", "BEGINNER", 3.0, "Press knees outward against the pads, pause, return slowly."],
  ["Cable Pull-Through", "GLUTES", "MACHINE", "INTERMEDIATE", 4.0, "Face away from a low rope, hinge, then snap hips forward squeezing glutes."],
  ["Cable Glute Kickback", "GLUTES", "MACHINE", "BEGINNER", 3.0, "Ankle strap on a low pulley, kick the leg straight back, squeeze, return."],
  ["Step-Up (weighted)", "LEGS", "DUMBBELLS", "INTERMEDIATE", 6.0, "Step onto a knee-high box driving through the front heel; alternate legs."],
  ["Step-Up (bodyweight)", "LEGS", "BODYWEIGHT", "BEGINNER", 5.0, "Step onto a stable surface, stand tall, step down with control."],
  ["Reverse Lunge", "LEGS", "BODYWEIGHT", "BEGINNER", 5.0, "Step back, lower the rear knee toward the floor, push through the front heel."],
  ["Curtsy Lunge", "GLUTES", "BODYWEIGHT", "INTERMEDIATE", 5.0, "Step back and across behind the front leg, lower, return."],
  ["Lateral Lunge", "LEGS", "BODYWEIGHT", "INTERMEDIATE", 5.0, "Step wide to one side, sit into that hip keeping the other leg straight."],
  ["Sissy Squat", "LEGS", "BODYWEIGHT", "ADVANCED", 5.0, "Rise onto toes, lean back and bend knees forward in one line, return."],
  ["Wall Sit", "LEGS", "BODYWEIGHT", "BEGINNER", 3.5, "Back flat on a wall, thighs parallel to the floor, hold."],
  ["Single-Leg Glute Bridge", "GLUTES", "BODYWEIGHT", "INTERMEDIATE", 4.0, "One foot planted, other leg extended; drive hips up, squeeze, lower."],
  ["Donkey Kick", "GLUTES", "BODYWEIGHT", "BEGINNER", 3.0, "On all fours, kick one heel toward the ceiling with a bent knee, squeeze."],
  ["Fire Hydrant", "GLUTES", "BODYWEIGHT", "BEGINNER", 3.0, "On all fours, lift one knee out to the side keeping hips square."],
  ["Band Lateral Walk", "GLUTES", "BANDS", "BEGINNER", 3.5, "Band above knees, quarter squat, step sideways keeping tension."],
  ["Band Glute Bridge", "GLUTES", "BANDS", "BEGINNER", 3.5, "Band above knees; bridge up while pressing knees out."],
  ["Kettlebell Goblet Reverse Lunge", "LEGS", "KETTLEBELL", "INTERMEDIATE", 6.0, "Hold the bell at your chest, alternate reverse lunges."],
  ["Kettlebell Deadlift", "LEGS", "KETTLEBELL", "BEGINNER", 5.0, "Bell between feet, hinge with a flat back, stand tall squeezing glutes."],
  ["Box Jump", "LEGS", "BODYWEIGHT", "ADVANCED", 8.0, "Jump onto a sturdy box, land softly, step down between reps."],
  ["Broad Jump", "LEGS", "BODYWEIGHT", "INTERMEDIATE", 7.0, "Swing arms and jump forward for distance, landing softly in a squat."],
  // Core
  ["Crunches", "CORE", "BODYWEIGHT", "BEGINNER", 3.0, "Hands by temples, curl shoulder blades off the floor, lower slowly."],
  ["Sit-Ups", "CORE", "BODYWEIGHT", "BEGINNER", 3.5, "Curl all the way up to sitting, lower one vertebra at a time."],
  ["Leg Raises", "CORE", "BODYWEIGHT", "INTERMEDIATE", 4.0, "Lying flat, raise straight legs to vertical, lower without arching the back."],
  ["Flutter Kicks", "CORE", "BODYWEIGHT", "BEGINNER", 4.0, "Legs straight and low, kick alternately with the lower back pressed down."],
  ["V-Ups", "CORE", "BODYWEIGHT", "ADVANCED", 5.0, "Simultaneously lift straight legs and torso to touch toes at the top."],
  ["Hollow Body Hold", "CORE", "BODYWEIGHT", "INTERMEDIATE", 3.5, "Lower back pressed to floor, arms and legs hovering, hold the banana shape."],
  ["Side Plank", "CORE", "BODYWEIGHT", "BEGINNER", 3.0, "Stack feet, lift hips high on one forearm, hold; switch sides."],
  ["Side Plank with Hip Dips", "CORE", "BODYWEIGHT", "INTERMEDIATE", 3.5, "From a side plank, dip the hip toward the floor and lift, repeat."],
  ["Plank Shoulder Taps", "CORE", "BODYWEIGHT", "INTERMEDIATE", 4.0, "High plank; tap opposite shoulder without letting hips sway."],
  ["Plank Up-Downs", "CORE", "BODYWEIGHT", "INTERMEDIATE", 4.5, "Move from forearm plank to high plank one arm at a time."],
  ["Ab Wheel Rollout", "CORE", "BODYWEIGHT", "ADVANCED", 4.5, "From knees, roll the wheel forward keeping the core braced, pull back."],
  ["Cable Crunch", "CORE", "MACHINE", "INTERMEDIATE", 3.5, "Kneel below a rope, crunch ribs toward hips against the cable."],
  ["Cable Woodchop", "CORE", "MACHINE", "INTERMEDIATE", 4.0, "Pull the handle diagonally across the body, rotating from the trunk."],
  ["Russian Twist (weighted)", "CORE", "DUMBBELLS", "INTERMEDIATE", 4.5, "Seated, lean back, rotate a dumbbell side to side with control."],
  ["Dead Hang", "CORE", "BODYWEIGHT", "BEGINNER", 2.5, "Hang from a bar with straight arms, shoulders active, breathe."],
  ["Toe Touches", "CORE", "BODYWEIGHT", "BEGINNER", 3.5, "Legs vertical, reach fingertips toward toes, lower shoulders slowly."],
  // Kettlebell & full body
  ["Kettlebell Goblet Press", "FULL_BODY", "KETTLEBELL", "INTERMEDIATE", 6.0, "From a goblet squat, stand and press the bell overhead in one flow."],
  ["Kettlebell Snatch", "FULL_BODY", "KETTLEBELL", "ADVANCED", 9.5, "Swing the bell back, then punch it overhead in one explosive motion."],
  ["Turkish Get-Up", "FULL_BODY", "KETTLEBELL", "ADVANCED", 6.0, "From lying to standing with the bell locked out overhead, step by step; reverse down."],
  ["Kettlebell Halo", "SHOULDERS", "KETTLEBELL", "BEGINNER", 3.0, "Circle the bell around your head keeping ribs down."],
  ["Thruster (dumbbell)", "FULL_BODY", "DUMBBELLS", "ADVANCED", 8.0, "Front squat straight into an overhead press in one motion."],
  ["Man Maker", "FULL_BODY", "DUMBBELLS", "ADVANCED", 8.5, "Push-up on dumbbells, row each side, jump in, clean and press overhead."],
  ["Farmer's Carry", "FULL_BODY", "DUMBBELLS", "BEGINNER", 5.0, "Heavy dumbbells at your sides, walk tall with short quick steps."],
  ["Bear Crawl", "FULL_BODY", "BODYWEIGHT", "INTERMEDIATE", 6.0, "Crawl forward on hands and toes, knees hovering, back flat."],
  ["Inchworm", "FULL_BODY", "BODYWEIGHT", "BEGINNER", 4.0, "Fold, walk hands out to a plank, walk feet in, stand tall."],
  ["Sled Push (or plate push)", "FULL_BODY", "MACHINE", "ADVANCED", 8.5, "Drive the sled forward with a low body angle and powerful steps."],
  ["Battle Ropes", "FULL_BODY", "MACHINE", "INTERMEDIATE", 8.0, "Alternate powerful arm waves keeping a quarter-squat stance."],
  ["Band Squat to Press", "FULL_BODY", "BANDS", "BEGINNER", 5.5, "Stand on the band, squat, then press the handles overhead as you stand."],
  // Cardio & conditioning
  ["Treadmill Incline Walk", "CARDIO", "CARDIO_MACHINE", "BEGINNER", 5.3, "Walk briskly at a 8-12% incline without holding the rails."],
  ["Treadmill Run", "CARDIO", "CARDIO_MACHINE", "INTERMEDIATE", 9.8, "Run at a steady conversational-to-moderate pace."],
  ["Elliptical Trainer", "CARDIO", "CARDIO_MACHINE", "BEGINNER", 5.5, "Smooth full strides using both arms and legs, moderate resistance."],
  ["Stair Climber", "CARDIO", "CARDIO_MACHINE", "INTERMEDIATE", 8.0, "Climb at a steady pace, tall posture, fingertips only on the rails."],
  ["Outdoor Cycling", "CARDIO", "BODYWEIGHT", "BEGINNER", 7.5, "Ride at a steady moderate effort; keep cadence smooth."],
  ["Swimming (freestyle, moderate)", "CARDIO", "BODYWEIGHT", "INTERMEDIATE", 8.0, "Continuous laps at a sustainable pace with relaxed breathing."],
  ["High Knees", "CARDIO", "BODYWEIGHT", "BEGINNER", 8.0, "Run in place driving knees to hip height, quick arm swing."],
  ["Butt Kicks", "CARDIO", "BODYWEIGHT", "BEGINNER", 7.0, "Jog in place kicking heels toward glutes rapidly."],
  ["Skaters", "CARDIO", "BODYWEIGHT", "INTERMEDIATE", 7.0, "Bound side to side landing on one leg, arms swinging across."],
  ["Shadow Boxing", "CARDIO", "BODYWEIGHT", "BEGINNER", 7.8, "Throw continuous punch combinations with footwork, stay light on your feet."],
  ["Dancing (freestyle/Zumba)", "CARDIO", "BODYWEIGHT", "BEGINNER", 6.5, "Keep moving to the music continuously; intensity to a light sweat."],
  ["Sprint Intervals", "CARDIO", "BODYWEIGHT", "ADVANCED", 12.0, "Sprint hard 20-30s, walk 60-90s; repeat."],
  ["Surya Namaskar (sun salutations)", "FULL_BODY", "BODYWEIGHT", "BEGINNER", 4.0, "Flow through the 12-step sequence continuously, breathing with each move."],
  ["Yoga Flow (vinyasa)", "FULL_BODY", "BODYWEIGHT", "BEGINNER", 3.3, "Continuous linked poses; keep transitions smooth and controlled."],
  ["Skipping (slow pace)", "CARDIO", "BODYWEIGHT", "BEGINNER", 8.8, "Easy continuous rope skips, soft knees and wrists doing the work."],
  ["Rowing Sprints", "CARDIO", "CARDIO_MACHINE", "ADVANCED", 9.5, "Hard 250-500 m intervals with easy paddling between."],
  // Curl family (straight & curved/EZ bar)
  ["Barbell Curl", "ARMS", "BARBELL", "BEGINNER", 3.2, "Shoulder-width underhand grip on a straight bar, curl with elbows pinned, lower for a slow count."],
  ["Curved Barbell Curl (EZ wide grip)", "ARMS", "BARBELL", "BEGINNER", 3.2, "Wide angled grip on the EZ (curved) bar, curl up keeping wrists neutral and elbows still."],
  ["Curved Barbell Curl (EZ close grip)", "ARMS", "BARBELL", "BEGINNER", 3.2, "Close angled grip on the EZ bar; curl focusing on the outer biceps, lower slowly."],
  ["Reverse Barbell Curl", "ARMS", "BARBELL", "INTERMEDIATE", 3.2, "Overhand grip, curl the bar keeping wrists straight — hits forearms and brachialis."],
  ["Drag Curl", "ARMS", "BARBELL", "INTERMEDIATE", 3.0, "Drag the bar up along your torso with elbows travelling back, squeeze at the top."],
  ["Barbell Curl 21s", "ARMS", "BARBELL", "ADVANCED", 3.5, "7 bottom-half reps, 7 top-half reps, 7 full reps — one continuous set."],
  ["Spider Curl", "ARMS", "BARBELL", "INTERMEDIATE", 3.0, "Chest on an incline bench, arms hanging vertical; curl the EZ bar strictly."],
  ["Preacher EZ-Bar Curl", "ARMS", "BARBELL", "BEGINNER", 3.0, "EZ bar on a preacher pad; curl up and lower to a full stretch without bouncing."],
  ["Cable Rope Hammer Curl", "ARMS", "MACHINE", "BEGINNER", 3.0, "Neutral grip on a rope from a low pulley; curl with constant tension."],
  ["Bayesian Cable Curl", "ARMS", "MACHINE", "INTERMEDIATE", 3.0, "Face away from a low pulley, arm slightly behind you; curl through a long stretch."],
  ["Cross-Body Hammer Curl", "ARMS", "DUMBBELLS", "BEGINNER", 3.0, "Curl each dumbbell across your body toward the opposite shoulder."],
  // More triceps & forearms
  ["Single-Arm Cable Pushdown", "ARMS", "MACHINE", "BEGINNER", 3.0, "One handle, elbow pinned; extend fully and control the return."],
  ["Dumbbell Kickback", "ARMS", "DUMBBELLS", "BEGINNER", 3.0, "Hinge forward, upper arm parallel to floor; extend the elbow fully behind you."],
  ["JM Press", "ARMS", "BARBELL", "ADVANCED", 4.0, "Hybrid of close-grip bench and skull crusher: lower the bar toward the chin with elbows tucked, press back."],
  ["Reverse Wrist Curl", "ARMS", "DUMBBELLS", "BEGINNER", 2.5, "Forearms on thighs palms-down; lift the knuckles up and lower slowly."],
  ["Plate Pinch Hold", "ARMS", "BODYWEIGHT", "BEGINNER", 2.5, "Pinch smooth plates between fingers and thumb, hold for time."],
  // More shoulders & chest
  ["Cable Rear Delt Fly", "SHOULDERS", "MACHINE", "INTERMEDIATE", 3.2, "Cross the cables at face height and pull outward/back with soft elbows."],
  ["Machine Lateral Raise", "SHOULDERS", "MACHINE", "BEGINNER", 3.0, "Arms under the pads; raise to shoulder height, lower slowly."],
  ["Plate Front Raise", "SHOULDERS", "BARBELL", "BEGINNER", 3.0, "Hold a plate at 3 and 9 o'clock, raise to eye level, lower with control."],
  ["Machine Incline Chest Press", "CHEST", "MACHINE", "BEGINNER", 4.0, "Seat set so handles start at upper-chest height; press up and together."],
  ["Weighted Dips", "CHEST", "BODYWEIGHT", "ADVANCED", 6.0, "Dips with a weight belt or dumbbell between the feet; lean forward for chest."],
  ["Smith Machine Bench Press", "CHEST", "MACHINE", "BEGINNER", 4.5, "Fixed bar path; lower to mid-chest and press, rack by rotating the bar."],
  // More back
  ["Inverted Row (feet elevated)", "BACK", "BODYWEIGHT", "INTERMEDIATE", 5.0, "Bar at hip height, feet on a bench; pull chest to the bar with a rigid body."],
  ["Meadows Row", "BACK", "BARBELL", "ADVANCED", 5.5, "Landmine bar, overhand grip on the sleeve; row with the elbow flaring out."],
  ["Seal Row (chest supported)", "BACK", "BARBELL", "INTERMEDIATE", 5.0, "Lie prone on a high bench; row the bar to the underside, no body English."],
  ["Trap Bar Deadlift", "BACK", "BARBELL", "INTERMEDIATE", 6.0, "Stand inside the hex bar; push the floor away and stand tall — beginner-friendlier pull."],
  ["Power Clean", "FULL_BODY", "BARBELL", "ADVANCED", 8.0, "Explosive pull from the floor, catch the bar on the front delts in a quarter squat."],
  // More legs & glutes
  ["Smith Machine Squat", "LEGS", "MACHINE", "BEGINNER", 5.0, "Fixed path squat; set feet slightly forward, squat to parallel."],
  ["Hip Thrust Machine", "GLUTES", "MACHINE", "BEGINNER", 5.0, "Back on the pad, drive the platform up with your hips, squeeze hard at lockout."],
  ["Adductor Machine (inner thigh)", "LEGS", "MACHINE", "BEGINNER", 3.0, "Squeeze knees together against the pads, return slowly."],
  ["Standing Calf Raise (machine)", "LEGS", "MACHINE", "BEGINNER", 3.2, "Shoulders under pads; rise high on toes, deep stretch at the bottom."],
  ["Walking Lunge (dumbbells)", "LEGS", "DUMBBELLS", "INTERMEDIATE", 6.0, "Dumbbells at sides; continuous alternating lunges walking forward."],
  ["Barbell Walking Lunge", "LEGS", "BARBELL", "ADVANCED", 6.5, "Bar on your back; long controlled lunge steps, torso tall."],
  ["Nordic Hamstring Curl", "LEGS", "BODYWEIGHT", "ADVANCED", 5.0, "Ankles anchored; lower your torso forward as slowly as possible, push back up."],
  ["Pistol Squat (assisted)", "LEGS", "BODYWEIGHT", "ADVANCED", 6.0, "One-leg squat holding a pole or strap for balance; build depth gradually."],
  ["Barbell Hip Thrust (heavy)", "GLUTES", "BARBELL", "INTERMEDIATE", 5.5, "Padded bar over hips, upper back on a bench; full hip extension every rep."],
  // More core
  ["Hanging Leg Raise (straight legs)", "CORE", "BODYWEIGHT", "ADVANCED", 5.0, "Hang from a bar; raise straight legs to hip height or above without swinging."],
  ["Pallof Press", "CORE", "MACHINE", "BEGINNER", 3.0, "Hold the cable at your chest side-on to the stack; press straight out resisting rotation."],
  ["Dumbbell Side Bend", "CORE", "DUMBBELLS", "BEGINNER", 3.0, "One dumbbell at your side; bend sideways and return using the obliques."],
  ["Dragon Flag (negative)", "CORE", "BODYWEIGHT", "ADVANCED", 5.5, "Grip a bench behind your head; lower a rigid body from vertical as slowly as possible."],
  ["Copenhagen Plank", "CORE", "BODYWEIGHT", "ADVANCED", 4.0, "Side plank with the top foot on a bench — inner-thigh and oblique hold."],
];
